### ISSUE TITLE
Modules - sequence of modules

### ISSUE THREAD

**Issue by reynas** [EricZimmerman/KapeFiles#93] opened 2019-07-11 06:55 UTC
Hi

I was wondering why the memory acquisition modules are always put last of the execution of modules. I tried putting it  (winpmem, dumpit)  first, but it seems it is skipping the modules that should be executed after the memory dump. The reason I wanted to executed the memory dump first is to keep the memory image as clean as possible, am I missing something?

Thanks!

**Comment by EricZimmerman** [comment] 2019-07-11 12:01
Please show me your command line and a list of module names so I can
investigate.

**Comment by reynas** [comment] 2019-07-11 12:57
PS C:\KAPE> .\kape.exe --msource C:\ --mdest C:\cases\KAPE-OUTPUT --mflush --module WinPmem,autoruns,DNSCache --debug
KAPE version 0.8.5.1 Author: Eric Zimmerman (kape@kroll.com)

KAPE directory: C:\KAPE
Command line: --msource C:\ --mdest C:\cases\KAPE-OUTPUT --mflush --module WinPmem autoruns DNSCache --debug
Enabled debug messages...
Validating configuration files
61 targets and 91 modules validated successfully
Using Module operations
        Flushing module destination directory 'C:\cases\KAPE-OUTPUT'
        Creating module destination directory 'C:\cases\KAPE-OUTPUT'
        WinPmem: Determining correct processor based export type 'dmp'...
        Found processor 'Executable: winpmem_3.2.exe, Cmd line: -o %destinationDirectory%/memory.dmp --volume_format raw -dd, Export: dmp'!
Discovered 1 processor to run.
Module name: WinPmem, Processor: Executable: winpmem_3.2.exe, Cmd line: -o %destinationDirectory%/memory.dmp --volume_format raw -dd, Export: dmp  , Category: Memory
Executing modules with file masks...
Executing remaining modules...
        Running 'winpmem_3.2.exe': -o C:\cases\KAPE-OUTPUT\Memory/memory.dmp --volume_format raw -dd
Executed 1 processor in 111.4628 seconds

Total execution time: 111.6019 seconds

**Comment by EricZimmerman** [comment] 2019-07-12 20:56
that looks like it worked fine to me. i see one processor run. do you have an example where it is not honoring the order?

**Comment by EricZimmerman** [comment] 2019-07-12 20:57
or are you saying you expect autoruns and dnscache to do something too? i assume autoruns and dnscache mkape files both exist in the modules directory?

**Comment by EricZimmerman** [comment] 2019-07-12 21:14
lots of things going on here.

first, everything is working fine for me here:

![image](https://user-images.githubusercontent.com/4265254/61158556-45eb3380-a4c7-11e9-8a5a-ff0502f2c7ac.png)

however, winpmem is not behaving properly for some reason in that it is not writing its output to standard info. when i run things manually, i get this:

![image](https://user-images.githubusercontent.com/4265254/61158602-716e1e00-a4c7-11e9-81d9-b5b3f1f976b7.png)

at least on my machine. no idea if this is an issue with winpmem or i need a reboot, but you can try it manually too.

@ecapuano can you verify things work as expected and also adjust the path in winpmem module to use a \ vs a / in the path to the dump file and do a PR?

"-o %destinationDirectory%/memory.dmp --volume_format raw -dd"

should be

"-o %destinationDirectory%\memory.dmp --volume_format raw -dd"

can you also change the name of the executable to something not version specific like winpmem.exe so that updates to the tool do not require the module to change?

Executable: winpmem_3.2.exe

should be

Executable: winpmem.exe

i reported the issue to winpmem project about loading things and no stdout, but other than that, things seem to be working fine here.

you can run the same execution but add --trace then zip and email me the output so i can check more stuff too if you like

**Comment by ecapuano** [comment] 2019-07-13 09:03
I tested the current version of the module and it works as expected, however I can confirm that WinPMem does not provide standard out when running via KAPE and I'm not sure why... That said, it dumps memory exactly as expected.

![image](https://user-images.githubusercontent.com/4219694/61169439-5fd35780-a555-11e9-9897-8a5001c3c0f6.png)


I tested with the `\` instead of `/` in the dump path but it produces an error during validation.

![image](https://user-images.githubusercontent.com/4219694/61169445-6e217380-a555-11e9-924e-9be29ae23fd6.png)

**Comment by EricZimmerman** [comment] 2019-07-13 12:28
ok thanks for confirming. can you try doubling up the \\ to see if that works? seems like its treating one as an escape sequence. i mean, it works as is, so you do not have to do anything.

the stdout and stderr issues tho are concerning and can be commented on here if you like:

https://github.com/Velocidex/c-aff4/issues/126

**Comment by reynas** [comment] 2019-07-13 22:18
OK, I do see a difference in your input/output (checking your powershell screenshot)
This one is mine: 
PS C:\KAPE> .\kape.exe --msource C:\ --mdest C:\cases\KAPE-OUTPUT --mflush --module **WinPmem,autoruns,DNSCache** --debug
KAPE version 0.8.5.1 Author: Eric Zimmerman (kape@kroll.com)

KAPE directory: C:\KAPE
Command line: --msource C:\ --mdest C:\cases\KAPE-OUTPUT --mflush --module **WinPmem autoruns DNSCache** --debug

As you can see, in the output from kape, it skips the commas for some reason, which causes kape to ignore the modules after the first one listed.

I justed tested with the normal windows command prompt instead of powershell, and this is working.

**Comment by EricZimmerman** [comment] 2019-07-13 23:27
Multiple targets or modules must be separated by commas without spaces. In your case everything after the first was just ignored. I'll close this.

**Closed by EricZimmerman** 2019-07-13 23:27 UTC
