### ISSUE TITLE
KAPE not copying locked files.

### ISSUE THREAD

**Issue by Beercow** [EricZimmerman/KapeFiles#150] opened 2019-10-11 12:59 UTC
** KAPE version # **
0.8.7.3

**Describe the bug**
According to KAPE's log, it finds a match for the file. Then it is deferred due to IOException. When KAPE starts to copy the deferred files it states "does not exist! Skipping!"

**To Reproduce**
run target  Symantec_AV_Logs

**Expected behavior**
Copy locked files.

**Screenshots**

**Additional context**
I've tried setting FollowSymbolicLinks, FollowReparsePoint and AlwaysAddToQueue to true. The problem still persists. 

![image](https://user-images.githubusercontent.com/10360919/66653010-a7bd5580-ebfc-11e9-92b4-ae352444a682.png)

![image](https://user-images.githubusercontent.com/10360919/66653176-0e427380-ebfd-11e9-8638-ab2d10a6adbc.png)

**Comment by EricZimmerman** [comment] 2019-10-11 13:11
I don't have that on my machine to be able to actually test it

what I would recommend is that you update the symantec logs file to not use the current path and then actually put the sequel in program data etc etc like you see to get around the whole symbolic link thing

Try that for me?

**Comment by Beercow** [comment] 2019-10-11 15:06
If I replace C:\ProgramData\Symantec\Symantec Endpoint Protection\CurrentVersion\Data\Logs with C:\ProgramData\Symantec\Symantec Endpoint Protection\14.2.1031.0100.105\Data\Logs it works just fine. Also to note. If the file is not locked, it is copied from C:\ProgramData\Symantec\Symantec Endpoint Protection\CurrentVersion without an issue.
![image](https://user-images.githubusercontent.com/10360919/66662519-9aa96200-ec0e-11e9-9032-9fc3afe69d10.png)

**Comment by EricZimmerman** [comment] 2019-10-11 15:23
Ok, the "proper" way to do reparse points is to put the actual path versus
the normal path as you had it initially.

Can you submit a PR?

Eric Zimmerman

Opinions stated, unless explicitly stated otherwise, are mine and not that
of my employer.

P // 501-313-3778

**Comment by Beercow** [comment] 2019-10-11 15:39
The problem with that is the actual path is not always known. I'll have to play around with wild cards. The CurrentVersion folder always points to the right location. If this is the "proper" to do reparse points, what is the FollowReparsePoint option for?

**Comment by EricZimmerman** [comment] 2019-10-11 16:20
Have you tried both the options independently of one another? See how the
box target looks for an example.

What do I need to install locally on my machine to have those logs?

**Comment by Beercow** [comment] 2019-10-11 18:43
I tried different combinations and in different orders with same result. You can get a trial version from here:
https://www.symantec.com/products/endpoint-protection

click on free trial

Not sure if it will help but here is the log from KAPE
[2019-10-11T164529_Console_Log_SFTP.txt](https://github.com/EricZimmerman/KapeFiles/files/3719180/2019-10-11T164529_Console_Log_SFTP.txt)

**Comment by EricZimmerman** [comment] 2019-10-18 17:51
i am installing this monstrosity of a program now to test, but i notice in your command line you have --tracing, when it should be --trace

**Comment by EricZimmerman** [comment] 2019-10-18 17:53
also, why not do something like

C:\ProgramData\Symantec\Symantec Endpoint Protection\*\Data\Logs

?

**Comment by EricZimmerman** [comment] 2019-10-18 18:14
currentVersion is a junction.

testing over next few days

**Comment by EricZimmerman** [comment] 2019-10-18 20:51
so this:

C:\ProgramData\Symantec\Symantec Endpoint Protection\*\Data\Logs

works fine and copies out the files.

the issue is the Symbolic link is buried in the middle of the path (the CurrentVersion value):

C:\ProgramData\Symantec\Symantec Endpoint Protection\CurrentVersion\Data\Logs

which causes KAPE to not be able to find it when doing a raw read.

so the solution is to just change CurrentVersion to * and do a PR. 

Problem solved!

the reparse and symlink options are for processing directories at the root that have those properties, so while this would work:

C:\ProgramData\Symantec\Symantec Endpoint Protection\CurrentVersion

it is not what you want unless you did a filemask of *.log or something so you didnt end up with way more than you want to.

so please try the * thing, test it, and if its good, do a PR, then close this.

thanks!

**Closed by EricZimmerman** 2019-10-18 20:51 UTC
