### ISSUE TITLE
Enhancement: architecture specific executables in modules

### ISSUE THREAD

**Issue by ecapuano** [EricZimmerman/KapeFiles#79] opened 2019-05-19 02:06 UTC
A few of the binaries I'm trying to build into KAPE modules have x86 and x64 variants. Would typically have to wrap these in a PowerShell script to detect architecture.

Would be awesome if there was a way to specify both versions of an Executable in a module and let KAPE pick the best one...

Perhaps `Executable` can be the default in all situations but if an x86 binary is provided and it is an x86 system, prefer the x86 executable.

example:
```
Processors:
    -
        Executable: my-binary-x64.exe
        Executable_x86: my-binary-x86.exe
```

**Comment by EricZimmerman** [comment] 2019-05-19 15:45
so i think what i will do here is this:

the default is 64bit, BUT, if x86 is detected AND there is an x86 version available, ill call that.

Executable: my-binary.exe # this is the default

but if there is a my-binary_x86.exe that is in the bin folder and its an x86 CPU, call that.

that way its "clean" for programs that work both ways and transparent for the most part.

thoughts?

**Comment by EricZimmerman** [comment] 2019-05-19 23:05
sent you a test build

**Comment by EricZimmerman** [comment] 2019-05-23 13:10
this is done. closing for now, pending any feedback that its not working as intended

**Closed by EricZimmerman** 2019-05-23 13:10 UTC
